config/routes.rb
Rails.application.routes.draw do
  resources :checkins do
    collection do
      get :history
      get :customers
      get :welcome
    end
  end

  resources :stores do
    collection do
      get :myStore
    end
  end

  devise_for :users, controllers: { registrations: 'users/registrations'}

  root to: 'stores#index'

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/store.rb
class Store < ApplicationRecord
  belongs_to :user
  has_many :checkins

  validates_presence_of :user_id
end

app/controllers/stores_controller.rb
class StoresController < ApplicationController
  before_action :set_store, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!


  # GET /stores
  # GET /stores.json
  def index
    @stores = if params[:title]
                Store.where('name like?', "%#{params[:title]}%")
               else
                 Store.all
               end
  end

  #Owner srores list
  def myStore
    @stores = Store.where(user_id: current_user.id)
  end


  # GET /stores/new
  def new
    @store = Store.new
  end


  # POST /stores
  # POST /stores.json
  def create
    @store = Store.new(store_params)
    @store.user_id = current_user.id
    current_user.update!(type: "Owner")

    respond_to do |format|
      if @store.save
         format.html { redirect_to myStore_stores_path, notice: 'Store was successfully created.' }
        format.json { render :show, status: :created, location: @store }
      else
        format.html { render :new }
        format.json { render json: @store.errors, status: :unprocessable_entity }
      end
    end
  end


  private
    # Use callbacks to share common setup or constraints between actions.
    def set_store
      @store = Store.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def store_params
      params.require(:store).permit(:user_id, :name, :location, :link, :title)
    end
end

app/helpers/stores_helper.rb
module StoresHelper
end

app/views/stores/_form.html.erb
<%= form_with(model: store, local: true) do |form| %>
  <% if store.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(store.errors.count, "error") %> prohibited this store from being saved:</h2>

      <ul>
        <% store.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :location %>
    <%= form.text_area :location %>
  </div>


  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/stores/index.html.erb
<p id="notice"><%= notice %></p>
</br>

<h3>Search by store name</h3>
<div >
  <%= form_tag(stores_path, :method => "get") do %>
    <%= text_field_tag(:title,nil, placeholder:"Search by store name") %>
  <% end %>
</div>

</br>
<h1>Stores</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Location</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @stores.each do |store| %>
      <tr>
        <td><%= store.name %></td>
        <td><%= store.location %></td>
        <%if current_user.owner? %>
        <td><%= link_to 'Edit', edit_store_path(store) %></td>
        <td><%= link_to 'Destroy', store, method: :delete, data: { confirm: 'Are you sure?' } %></td>
        <%end%>
        <%if current_user.customer? %>
        <td><%= link_to 'Chick in', new_checkin_path(store_id: store.id) %></td>
          <%end%>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

app/views/stores/myStore.html.erb
<p id="notice"><%= notice %></p>

<h1>My stores</h1>

<table>
  <tbody>
  <% @stores.each do |store| %>
    <tr>
      <td><%= store.name %></td>
      <td><%= link_to "Customers list",customers_checkins_path(store_id: store.id) %></td>
    </tr>
  <% end %>
  </tbody>
</table>

<br>
<%= link_to "new store", new_store_path  %>


app/views/stores/new.html.erb
<h1>New Store</h1>

<%= render 'form', store: @store %>

<%= link_to 'Back', stores_path %>