config/routes.rb
Rails.application.routes.draw do
  resources :checkins do
    collection do
      get :history
      get :customers
      get :welcome
    end
  end

  resources :stores do
    collection do
      get :myStore
    end
  end

  devise_for :users, controllers: { registrations: 'users/registrations'}

  root to: 'stores#index'

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/checkin.rb
class Checkin < ApplicationRecord
  belongs_to :store
  belongs_to :user

  validates_presence_of :store_id
  validates_presence_of :user_id
  end

app/controllers/checkins_controller.rb
class CheckinsController < ApplicationController
  before_action :set_checkin, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!



  #customer check in list
  def history
    @checkins = Checkin.where(user_id: current_user.id)
  end

  #list of store customers
  def customers
    @checkin = Checkin.where(store_id: params[:store_id]).all
  end

  # GET /checkins/new
  def new
    @checkin = Checkin.new
  end

  # GET /checkins/1/edit
  def edit
  end

  # POST /checkins
  # POST /checkins.json
  def create

    @checkin = Checkin.new(checkin_params)
    @checkin.user_id = current_user.id
    @checkin.datetime = DateTime.now

    respond_to do |format|
      if @checkin.save!
        format.html { redirect_to stores_path, notice: 'Checkin was successfully created.' }
        format.json { render :show, status: :created, location: @checkin }
      else
        format.html { render :new }
        format.json { render json: @checkin.errors, status: :unprocessable_entity }
      end
    end
  end


  private
    # Use callbacks to share common setup or constraints between actions.
    def set_checkin
      @checkin = Checkin.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def checkin_params
      params.require(:checkin).permit(:store_id, :user_id, :temp, :datetime)
    end
end

app/helpers/checkins_helper.rb
module CheckinsHelper
end

app/views/checkins/_form.html.erb
<%= form_with(model: checkin, local: true) do |form| %>
  <% if checkin.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(checkin.errors.count, "error") %> prohibited this checkin from being saved:</h2>

      <ul>
        <% checkin.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.hidden_field :store_id, value: params[:store_id] %>
  </div>

  <div class="field">
    <%= form.label :temp %>
    <%= form.text_field :temp %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/checkins/customers.html.erb
<p id="notice"><%= notice %></p>

<h1>Check ins:</h1>

<table>
  <thead>
  <tr>
    <th>Costumer</th>
    <th>NRIC</th>
    <th>Temp</th>
    <th>Datetime</th>
    <th colspan="3"></th>
  </tr>
  </thead>
  <tbody>
  <% @checkin.each do |checkin| %>
    <tr>
      <td><%= checkin.user.name %></td>
      <td><%= checkin.user.nric %></td>
      <td><%= checkin.temp %></td>
      <td><%= checkin.datetime %></td>
    </tr>
  <% end %>
  </tbody>
</table>

<br>


app/views/checkins/history.html.erb
<p id="notice"><%= notice %></p>

<h1>Checkins</h1>

<table>
  <thead>
  <tr>
    <th>Store</th>
    <th>Temp</th>
    <th>Datetime</th>
    <th colspan="3"></th>
  </tr>
  </thead>

  <tbody>
  <% @checkins.each do |checkin| %>
    <tr>
      <td><%= checkin.store.name%></td>
      <td><%= checkin.temp%></td>
      <td><%= checkin.datetime %></td>
    </tr>
  <% end %>
  </tbody>
</table>

<br>


app/views/checkins/new.html.erb
<h1>New Checkin</h1>

<%= render 'form', checkin: @checkin %>

<%= link_to 'Back', checkins_path %>

app/views/checkins/welcome.erb
<p id="notice"><%= notice %></p>

 <h1><%= link_to "Check in", stores_path  %>  /  <%= link_to "Owner", myStore_stores_path  %></h1>